spring:
  application:
    name: SpringBootMybatisQuiz
  #jsp
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
  #mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tea
    username: angel
    password: a1234
#tomcat port
server:
  port: 9001
#mybatis
mybatis:
  type-aliases-package: book.data
  mapper-locations:
  - /mapper/**/*.xml